# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A order-located function
#' @description A function returns the index (starting with 0) of the i-th smallest element in the vector in its i-th element
#' @param vec a numeric vector
#' @return an integer vector with i-th element equaling the index (starting with 0) of the i-the smallest element in the input vector
#' @examples
#' \dontrun{
#' x<-c(1,3,2,6)
#' ordered(x)}
#' @export
ordered <- function(vec) {
    .Call('_StatComp22003_ordered', PACKAGE = 'StatComp22003', vec)
}

#' @title Predict the label of a sample using our tree
#' @description Predict the label of a sample using our tree
#' @param x_test A vector, the sample 
#' @param node_info A tree producted by tree_create
#' @return The predicted label of x_test
#' @examples
#' \dontrun{
#' data(iris)
#' iris_data <- as.matrix(iris[1:100,-5])
#' iris_label <- as.numeric(iris[1:100,5])-1
#' set.seed(15)
#' ind <- 1:100
#' ind_tr <- sample(ind,60)
#' ind_test <- ind[-ind_tr]
#' t <- tree_create(x=iris_data,y=iris_label,q=4,random_split=F)
#' pre <- sapply(1:40,tree_predict(t,iris_data[ind_test[i],]))
#' }
#' @export
tree_predict <- function(node_info, x_test) {
    .Call('_StatComp22003_tree_predict', PACKAGE = 'StatComp22003', node_info, x_test)
}

#' @title A random-split method to build a tree for binary classification
#' @description We use recursive partition to build a tree for binary classification problem. We take the mean-square error instead of gini as the split criteria. We can choose to build a random-split tree or a deterministic tree by setting the parameter \code{q} and \code{random_split}. This function is the base for a random forest.
#' @param x Numeric matrix, with \code{n} rows and \code{p} columns.
#' @param y The binary label, either 0 or 1.
#' @param q The number of dimensions of \code{x} to be considered for split at each node. (Default q=\code{sqrt(p)})
#' @param s_min If the number of sample on the node is less than s_min (default 1), latter split will be ended.
#' @param random_split \code{T} or \code{F}. \code{T} means that we would like to randomly choose \code{q} dimensions of \code{x} to split at each node. \code{F} means we just split in q dimensions randomly chosen at the beginning.
#' @return A tree saved as a list contains information
#' @examples
#' \dontrun{
#' data(iris)
#' iris_data <- as.matrix(iris[1:100,-5])
#' iris_label <- as.numeric(iris[1:100,5])-1
#' set.seed(15)
#' ind <- 1:100
#' ind_tr <- sample(ind,60)
#' ind_test <- ind[-ind_tr]
#' t <- tree_create(x=iris_data,y=iris_label,q=4,random_split=F)
#' pre <- sapply(1:40,tree_predict(t,iris_data[ind_test[i],]))
#' }
#' @export
tree_create <- function(x, y, q = NA_integer_, s_min = 1L, random_split = TRUE) {
    .Call('_StatComp22003_tree_create', PACKAGE = 'StatComp22003', x, y, q, s_min, random_split)
}

